/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        res = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        moin = new javax.swing.JButton();
        prod = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        vrgl = new javax.swing.JButton();
        sgn = new javax.swing.JButton();
        frac = new javax.swing.JButton();
        calculer = new javax.swing.JButton();
        vrgl1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(102, 102, 102));
        b1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(102, 102, 102));
        b7.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(102, 102, 102));
        b4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(102, 102, 102));
        b2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(102, 102, 102));
        b5.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(102, 102, 102));
        b8.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(102, 102, 102));
        b3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(102, 102, 102));
        b6.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(102, 102, 102));
        b9.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(102, 102, 102));
        plus.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        moin.setBackground(new java.awt.Color(102, 102, 102));
        moin.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        moin.setForeground(new java.awt.Color(255, 255, 255));
        moin.setText("-");
        moin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moinActionPerformed(evt);
            }
        });

        prod.setBackground(new java.awt.Color(102, 102, 102));
        prod.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        prod.setForeground(new java.awt.Color(255, 255, 255));
        prod.setText("*");
        prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(102, 102, 102));
        b0.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        vrgl.setBackground(new java.awt.Color(102, 102, 102));
        vrgl.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        vrgl.setForeground(new java.awt.Color(255, 255, 255));
        vrgl.setText(".");
        vrgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrglActionPerformed(evt);
            }
        });

        sgn.setBackground(new java.awt.Color(102, 102, 102));
        sgn.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        sgn.setForeground(new java.awt.Color(255, 255, 255));
        sgn.setText("+/-");
        sgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgnActionPerformed(evt);
            }
        });

        frac.setBackground(new java.awt.Color(102, 102, 102));
        frac.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        frac.setForeground(new java.awt.Color(255, 255, 255));
        frac.setText("/");
        frac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fracActionPerformed(evt);
            }
        });

        calculer.setBackground(new java.awt.Color(102, 102, 102));
        calculer.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        calculer.setForeground(new java.awt.Color(255, 255, 255));
        calculer.setText("Calculer");
        calculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerActionPerformed(evt);
            }
        });

        vrgl1.setBackground(new java.awt.Color(102, 102, 102));
        vrgl1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        vrgl1.setForeground(new java.awt.Color(255, 255, 255));
        vrgl1.setText("CLR/ON");
        vrgl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrgl1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Casio");

        jButton1.setText("OFF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vrgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(vrgl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sgn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prod, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(frac, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(calculer, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(res))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frac, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sgn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vrgl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrgl1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
    }//GEN-LAST:event_resActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
String ch =res.getText();
        res.setText(ch+"6");    }//GEN-LAST:event_b6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String ch =res.getText();
        res.setText(ch+"1");
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String ch =res.getText();
        res.setText(ch+"2");
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String ch =res.getText();
        res.setText(ch+"3");
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
String ch =res.getText();
        res.setText(ch+"4");    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
String ch =res.getText();
        res.setText(ch+"5");    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
String ch =res.getText();
        res.setText(ch+"7");    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
String ch =res.getText();
        res.setText(ch+"8");    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
String ch =res.getText();
        res.setText(ch+"9");    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
String ch =res.getText();
        res.setText(ch+"0");    }//GEN-LAST:event_b0ActionPerformed

    private void vrglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrglActionPerformed
String ch =res.getText();
        res.setText(ch+".");    }//GEN-LAST:event_vrglActionPerformed

    private void sgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgnActionPerformed
Float x = Float.parseFloat(res.getText());
x*=-1;
res.setText(x+"");
    }//GEN-LAST:event_sgnActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
String ch =res.getText();
        if (ch.contains("+"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("+")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("+")+1,ch.length()));
            res.setText(""+(v1+v2));
        } 
        else if (ch.contains("-"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("-")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("-")+1,ch.length()));
            res.setText(""+(v1-v2));
        } 
        else if (ch.contains("*"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("*")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("*")+1,ch.length()));
            res.setText(""+(v1*v2));
        } 
                else if (ch.contains("/"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("/")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("/")+1,ch.length()));
            res.setText(""+(v1/v2));
        }
        res.setText(res.getText()+"+") ;
    }//GEN-LAST:event_plusActionPerformed

    private void moinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinActionPerformed
       String ch =res.getText();
        if (ch.contains("+"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("+")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("+")+1,ch.length()));
            res.setText(""+(v1+v2));
        } 
        else if (ch.contains("-"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("-")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("-")+1,ch.length()));
            res.setText(""+(v1-v2));
        } 
        else if (ch.contains("*"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("*")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("*")+1,ch.length()));
            res.setText(""+(v1*v2));
        } 
                else if (ch.contains("/"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("/")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("/")+1,ch.length()));
            res.setText(""+(v1/v2));
        }
        res.setText(res.getText()+"-") ;
    }//GEN-LAST:event_moinActionPerformed

    private void prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodActionPerformed
String ch =res.getText();
        if (ch.contains("+"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("+")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("+")+1,ch.length()));
            res.setText(""+(v1+v2));
        } 
        else if (ch.contains("-"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("-")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("-")+1,ch.length()));
            res.setText(""+(v1-v2));
        } 
        else if (ch.contains("*"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("*")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("*")+1,ch.length()));
            res.setText(""+(v1*v2));
        } 
                else if (ch.contains("/"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("/")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("/")+1,ch.length()));
            res.setText(""+(v1/v2));
            
        }
       res.setText(res.getText()+"*") ;
    }//GEN-LAST:event_prodActionPerformed

    private void fracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fracActionPerformed
String ch =res.getText();
        if (ch.contains("+"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("+")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("+")+1,ch.length()));
            res.setText(""+(v1+v2));
        } 
        else if (ch.contains("-"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("-")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("-")+1,ch.length()));
            res.setText(""+(v1-v2));
        } 
        else if (ch.contains("*"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("*")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("*")+1,ch.length()));
            res.setText(""+(v1*v2));
        } 
                else if (ch.contains("/"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("/")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("/")+1,ch.length()));
            res.setText(""+(v1/v2));
        }
        res.setText(res.getText()+"/") ;
    }//GEN-LAST:event_fracActionPerformed

    private void calculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerActionPerformed
String ch =res.getText();
        if (ch.contains("+"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("+")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("+")+1,ch.length()));
            res.setText(""+(v1+v2));
        } 
        else if (ch.contains("-"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("-")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("-")+1,ch.length()));
            res.setText(""+(v1-v2));
        } 
        else if (ch.contains("*"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("*")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("*")+1,ch.length()));
            res.setText(""+(v1*v2));
        } 
                else if (ch.contains("/"))
        {Float v1=Float.parseFloat(ch.substring(0, ch.indexOf("/")));
        Float v2=Float.parseFloat(ch.substring(ch.indexOf("/")+1,ch.length()));
            res.setText(""+(v1/v2));
        }    }//GEN-LAST:event_calculerActionPerformed

    private void vrgl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrgl1ActionPerformed
       res.setText("0");
    }//GEN-LAST:event_vrgl1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        res.setText("power__off");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton calculer;
    private javax.swing.JButton frac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moin;
    private javax.swing.JButton plus;
    private javax.swing.JButton prod;
    private javax.swing.JTextField res;
    private javax.swing.JButton sgn;
    private javax.swing.JButton vrgl;
    private javax.swing.JButton vrgl1;
    // End of variables declaration//GEN-END:variables
}
